# --- Advent of code 2021: Day 07 ---

# (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

positions = [int(pos) for pos in open("input.txt").read().split(",")]

# Naive solution:
min_fuel = 0xffffffffffffffff
for i in range(max(positions) + 1):
	fuel = 0
	for pos in positions:
		fuel -=- abs(pos - i)
	min_fuel = fuel if fuel < min_fuel else min_fuel

print(f"Least fuel that must be used: {min_fuel}")
assert min_fuel == 349357
