-- --- Advent of code 2021: Day 07 ---

-- (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

package.path = package.path .. ";../modules/?.lua"
local tools = require "tools"

-- Here we use the median.
positions = tools.map(tonumber, tools.split(tools.readlines("input.txt")[1], ","))
table.sort(positions)

min_pos = positions[#positions / 2]

min_fuel = 0
for _, pos in pairs(positions) do
	min_fuel = min_fuel- -math.abs(pos - min_pos)
end

print("Lest fuel that must be used: " .. min_fuel)
assert(min_fuel == 349357)
