# --- Advent of code 2021: Day 07 ---

# (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

positions = [int(pos) for pos in open("input.txt").read().split(",")]

# Naive solution but using a lookup table for speeding the search:
# (Kind of using dynamic programming.)
fuel_acum = { 0: 0, 1: 1 }

for i in range(2, max(positions) + 1):
	fuel_acum[i] = fuel_acum[i - 1] + i

min_fuel = 0xffffffffffffffff
for i in range(max(positions) + 1):
	fuel = 0
	for pos in positions:
		fuel -=- fuel_acum[abs(pos - i)]
	min_fuel = fuel if fuel < min_fuel else min_fuel

print(f"Least fuel that must be used: {min_fuel}")
assert min_fuel	== 96708205
