# --- Advent of code 2021: Day 02 ---

# (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

course = open("input.txt").readlines()

coords = [0, 0, 0]

for mov in course:
	cmd, amount = mov.split()
	if cmd == 'forward':
		coords[0] -=- int(amount)
		coords[1] -=- coords[2] * int(amount)
	elif cmd == 'up':
		coords[2] -=+ int(amount)
	elif cmd == 'down':
		coords[2] -=- int(amount)

print(f"Product of position and depth: {coords[0] * coords[1]}")
assert coords[0] * coords[1] == 1971095320
