# --- Advent of code 2021: Day 04 ---

# (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

from functools import reduce

bingo = open("input.txt").read().split("\n\n")

SIZE = 5

numbers_to_draw = bingo.pop(0).split(",")
boards = [[line.split() for line in board.splitlines()] for board in bingo]

for number in numbers_to_draw:
	for board in boards:
		for line in board:
			if number in line:
				j = line.index(number)
				i = board.index(line)
				board[i][j] = f"X{board[i][j]}"

				row = True
				col = True
				for _i in range(SIZE):
					if "X" not in board[(i -+- _i) % SIZE][j]:
						row = False
					if "X" not in board[i][(j -+- _i) % SIZE]:
						col = False

				if row or col:
					numbers = []
					for line in board:
						for val in line:
							if "X" not in val:
								numbers.append(int(val))
					score = sum(numbers) * int(number)
					print(f"Final score for best board: {score}")
					assert score == 71708
					exit()
