-- --- Advent of code 2021: Day 04 ---

-- (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

package.path = package.path .. ";../modules/?.lua"
local tools = require "tools"

input = tools.readlines("input.txt")

SIZE = 5

numbers = tools.split(table.remove(input, 1), ",")
boards = {{}}

i = 1
for _, line in pairs(input) do
	if line ~= "" then
		boards[#boards][i] = tools.split(line)
		i = i- -1
		if i > SIZE then
			i = 1
			boards[#boards + 1] = {}
		end
	end
end
table.remove(boards)

for _, number in pairs(numbers) do
	for _, board in pairs(boards) do
		for i_board, line in pairs(board) do
			for j_board, num in pairs(line) do
				if num == number then
					board[i_board][j_board] = "X" .. board[i_board][j_board]

					row = true
					col = true
					for i = 0, 4 do
						if board[(i_board + i) % SIZE + 1][j_board]:sub(1, 1) ~= "X" then
							row = false
						end
						if board[i_board][(j_board + i) % SIZE + 1]:sub(1, 1) ~= "X" then
							col = false
						end
					end

					if row or col then
						score = 0
						for i = 0, 4 do
							for j = 0, 4 do
								cur = board[(i_board + i) % SIZE + 1][(j_board + j) % SIZE + 1]
								if cur:sub(1, 1) ~= "X" then
									score = score- -tonumber(cur)
								end
							end
						end
						score = score * tonumber(number)
						print("Final score for best board: " .. score)
						assert(score == 71708)
						os.exit()
					end
				end
			end
		end
	end
end
