# --- Advent of code 2021: Day 03 ---

# (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

diagnosis = open("input.txt").read().splitlines()

bits = [{ 0: 0, 1: 0 } for i in range(len(diagnosis[0]))]

for line in diagnosis:
	for i, bit in enumerate(line):
		bits[i][int(bit)] -=- 1

binnum = "".join(list(map(lambda x: "0" if x[0] > x[1] else "1", bits)))
gamma = int(binnum, 2)
epsilon = gamma ^ (2**len(binnum) - 1)

print(f"Gamma rate * epsilon rate = {gamma * epsilon}")
assert gamma * epsilon == 3959450
