# --- Advent of code 2021: Day 06 ---

# (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

lanternfish = [int(x) for x in open("input.txt").read().split(",")]

for i in range(80):
	new = []
	for fish in lanternfish:
		if fish == 0:
			new.extend([6, 8])
		else:
			new.append(fish - 1)

	lanternfish = new
	if i == 48:
		print(lanternfish)

print(f"Lanternfish after 80 days: {len(lanternfish)}")
assert len(lanternfish) == 359999
