-- --- Advent of code 2021: Day 06 ---

-- (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

package.path = package.path .. ";../modules/?.lua"
local  tools = require "tools"

lanternfish = tools.map(tonumber, tools.split(tools.readlines("input.txt")[1], ","))

total_fish = {}
for offset = 0, 8 do
	total_fish[offset] = 0
end
for _, offset in pairs(lanternfish) do
	total_fish[offset + 1] = total_fish[offset + 1]- -1
end

for i = 1, 256 do
	fish = total_fish[i % 7]

	total_fish[i % 7] = total_fish[i % 7]- -total_fish[7]
	total_fish[7] = total_fish[8]
	total_fish[8] = fish
end

count = tools.reduce(function (a) return a end, total_fish) + total_fish[0]

print("Lanternfish after 256 days: " .. count)
assert(count == 1631647919273)
