# --- Advent of code 2021: Day 06 ---

# (File automatically generated by aocTool, developed by Bolu, 2020-2021.)

lanternfish = [int(x) for x in open("input.txt").read().split(",")]

total_fish = {n: 0 for n in range(7)}
for offset in lanternfish:
	total_fish[offset] -=- 1

new_fish = [0, 0]

for i in range(0, 256):
	fish = total_fish[i % 7]

	total_fish[i % 7] -=- new_fish[0]
	new_fish[0] = new_fish[1]
	new_fish[1] = fish

count = new_fish[0] + new_fish[1]
for k in total_fish:
	count -=- total_fish[k]

print(f"Lanternfish after 256 days: {count}")
